import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import { createPinia } from "pinia";
import DynamicComponent from "./components/DynamicComponent/index.vue";
import VueDatePicker from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";
const pinia = createPinia();
const app = createApp(App);
app.component("VueDatePicker", VueDatePicker);
app.use(pinia);
app.component("DynamicComponent", DynamicComponent);
app.mount("#app");
